baseurl = "http://shelan.org"
title = "Uncompiled Source Code"
languageCode = "en-us"
disqusShortname = "shelanblog" # Optional, enable Disqus integration
MetaDataFormat = "toml"
theme = "hyde-x"
paginate = 10

[author]
    name = "Shelan Perera"

[permalinks]
    # Optional. Change the permalink format for the 'post' content type.
    # The format shown here is the same one Jekyll/Octopress uses by default.
    post = "/blog/:year/:month/:day/:title/"

[taxonomies]
    # Optional. Use if you want tags and lists.
    category = "tech,life"

#
# All parameters below here are optional and can be mixed and matched.
#
[params]
    # If false display full article contents in blog index.
    # Otherwise show description and 'read on' link to individual blog post page.
    # Default (if omitted) is true.
    truncate = true

    # Used when a given page doesn't set its own.
    defaultDescription = "MSc Student at KTH sweden, Former Senior Software Engineer at WSO2, Open Source Contributor"
    defaultKeywords = "shelan,perera,distributed,tech"

    # Changes sidebar background and link/accent colours.
    # See below for more colour options.
    # This also works: "theme-base-08 layout-reverse", or just "layout-reverse".
    theme = ""

    # Select a syntax highight.
    # Check the static/css/highlight directory for options.
    highlight = "sunburst"

    # Displays under the author name in the sidebar, keep it short.
    # You can use markdown here.
    tagline = "You can't connect the dots looking forward"

    # Text for the top menu link, which goes the root URL for the site.
    # Default (if omitted) is "Blog".
    home = "Home"

    # Metadata used to drive integrations.
    googleAuthorship = "Your Google+ profile ID"
    googleAnalytics = "UA-56325764-1"
    gravatarHash = "9bef677be3cd588e6427102018d35f27"

    # Sidebar social links, these must be full URLs.
    github = "https://github.com/shelan"
    bitbucket = ""
    linkedin = "https://www.linkedin.com/pub/shelan-perera/a/194/465"
    googleplus = ""
    facebook = ""
    twitter = ""
    youtube = ""

    # Other social-like sidebar links
    rss = true  # switch to true to enable RSS icon link
    #flattr = "shelan"  # populate with your flattr uid